# Generated by Django 5.2.17 on 2026-08-22 12:52

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nomi')),
                ('scope', models.CharField(blank=True, max_length=180, verbose_name='ko‘lami')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='foydalanuvchilar soni')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'rollar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='kalit')),
                ('label', models.CharField(max_length=180, verbose_name='nomi')),
                ('hint', models.CharField(blank=True, max_length=250, verbose_name='izoh')),
                ('kind', models.CharField(choices=[('switch', 'Yoqish/o‘chirish'), ('number', 'Raqamli qiymat')], default='switch', max_length=16, verbose_name='turi')),
                ('number_value', models.IntegerField(blank=True, null=True, verbose_name='qiymati')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='yoqilgan')),
            ],
            options={
                'verbose_name': 'sozlama',
                'verbose_name_plural': 'sozlamalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='login')),
                ('full_name', models.CharField(max_length=180, verbose_name='F.I.Sh')),
                ('unit', models.CharField(blank=True, max_length=180, verbose_name='tashkilot / bo‘lim')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('status', models.CharField(choices=[('Faol', 'Faol'), ('Bloklangan', 'Bloklangan')], default='Faol', max_length=16, verbose_name='holati')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodim')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='qo‘shilgan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='roli')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_login', models.CharField(max_length=64, verbose_name='login')),
                ('role_name', models.CharField(blank=True, max_length=120, verbose_name='roli')),
                ('action', models.CharField(max_length=250, verbose_name='amal')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('is_success', models.BooleanField(default=True, verbose_name='bajarildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'audit yozuvi',
                'verbose_name_plural': 'audit jurnali',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
