# Generated by Django 5.2.17 on 2026-08-22 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='kompaniya nomi')),
                ('direction', models.CharField(max_length=90, verbose_name='yo‘nalishi')),
                ('employment_type', models.CharField(choices=[('Rasmiy shartnoma', 'Rasmiy shartnoma'), ('Norasmiy bandlik', 'Norasmiy bandlik')], default='Rasmiy shartnoma', max_length=24, verbose_name='shartnoma')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='yuborilgan migrantlar')),
                ('remittance_amount', models.PositiveIntegerField(default=0, verbose_name='jo‘natma, mln $')),
                ('status', models.CharField(choices=[('Tasdiqlangan', 'Tasdiqlangan'), ('Kuzatuvda', 'Kuzatuvda'), ('Cheklangan', 'Cheklangan')], default='Kuzatuvda', max_length=16, verbose_name='holati')),
                ('countries', models.ManyToManyField(blank=True, related_name='employers', to='geography.country', verbose_name='qaysi davlatlarga yuboradi')),
            ],
            options={
                'verbose_name': 'ish beruvchi',
                'verbose_name_plural': 'ish beruvchilar',
                'ordering': ['-sent_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('pinfl', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat bo‘lishi kerak')], verbose_name='PINFL')),
                ('full_name', models.CharField(db_index=True, max_length=180, verbose_name='F.I.Sh')),
                ('nationality', models.CharField(blank=True, max_length=60, verbose_name='millati')),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Voyaga yetmagan', 'Voyaga yetmagan')], default='Erkak', max_length=24, verbose_name='jinsi')),
                ('speciality', models.CharField(blank=True, max_length=90, verbose_name='mutaxassisligi')),
                ('purpose', models.CharField(choices=[('Ishlash (rasmiy)', 'Ishlash (rasmiy)'), ('Ishlash (norasmiy)', 'Ishlash (norasmiy)'), ('O‘qish', 'O‘qish'), ('Davolanish', 'Davolanish'), ('Sayohat', 'Sayohat'), ('Doimiy yashash', 'Doimiy yashash')], default='Ishlash (rasmiy)', max_length=32, verbose_name='chiqish maqsadi')),
                ('remittance_band', models.CharField(blank=True, max_length=32, verbose_name='pul jo‘natmalari')),
                ('marital_status', models.CharField(blank=True, max_length=40, verbose_name='oilaviy ahvoli')),
                ('health_status', models.CharField(choices=[('Sog‘lom', 'Sog‘lom'), ('Surunkali kasallik', 'Surunkali kasallik'), ('Nogironlik', 'Nogironlik')], default='Sog‘lom', max_length=32, verbose_name='sog‘lig‘i')),
                ('is_convicted', models.BooleanField(default=False, verbose_name='sudlangan')),
                ('employer_name', models.CharField(blank=True, max_length=180, verbose_name='ish beruvchi')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='xorijdagi manzil')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('legal_status', models.CharField(choices=[('Xavf yo‘q', 'Xavf yo‘q'), ('Qidiruvda', 'Qidiruvda'), ('Jazoni o‘tamoqda', 'Jazoni o‘tamoqda'), ('Bedarak yo‘qolgan', 'Bedarak yo‘qolgan')], default='Xavf yo‘q', max_length=32, verbose_name='holati')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='risk ball')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='chiqish sanasi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrants', to='geography.country', verbose_name='qabul qiluvchi davlat')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrants', to='geography.region', verbose_name='chiqqan hududi')),
            ],
            options={
                'verbose_name': 'migrant',
                'verbose_name_plural': 'migrantlar',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['legal_status'], name='registry_mi_legal_s_d83afe_idx'), models.Index(fields=['gender'], name='registry_mi_gender_3b72bc_idx')],
            },
        ),
    ]
