# Generated by Django 5.2.17 on 2026-08-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrants', to='registry.employer', verbose_name='ish beruvchi'),
        ),
        migrations.AlterField(
            model_name='migrant',
            name='employer_name',
            field=models.CharField(blank=True, help_text='Reyestrda bo‘lmagan tashkilot uchun — erkin matn', max_length=180, verbose_name='ish beruvchi (matn)'),
        ),
    ]
