# Generated by Django 5.2.18 on 2026-10-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geography",
            "0002_country_consulate_helped_country_consulate_requests_and_more",
        ),
        ("registry", "0002_migrant_employer_alter_migrant_employer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrant",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="migrants",
                to="geography.district",
                verbose_name="chiqqan tumani",
            ),
        ),
    ]
