# Generated by Django 5.2.17 on 2026-08-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='manba nomi')),
                ('status', models.CharField(choices=[('ulangan', 'Ulangan'), ('sinovda', 'Sinovda'), ('rejada', 'Rejada')], default='ulangan', max_length=16, verbose_name='holati')),
            ],
            options={
                'verbose_name': 'ma’lumot manbai',
                'verbose_name_plural': 'ma’lumot manbalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='kodi')),
                ('name', models.CharField(max_length=120, verbose_name='nomi')),
                ('flag', models.CharField(blank=True, max_length=8, verbose_name='bayrog‘i')),
                ('hub', models.CharField(blank=True, max_length=120, verbose_name='asosiy shahri')),
                ('latitude', models.FloatField(verbose_name='kengligi')),
                ('longitude', models.FloatField(verbose_name='uzunligi')),
                ('azimuth', models.PositiveSmallIntegerField(default=0, verbose_name='yo‘nalish burchagi')),
                ('distance_km', models.PositiveIntegerField(default=0, verbose_name='masofa, km')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='jami migrantlar')),
                ('departed', models.PositiveIntegerField(default=0, verbose_name='chiqqanlar')),
                ('returned', models.PositiveIntegerField(default=0, verbose_name='qaytganlar')),
                ('work', models.PositiveIntegerField(default=0, verbose_name='ishlash')),
                ('study', models.PositiveIntegerField(default=0, verbose_name='o‘qish')),
                ('medical', models.PositiveIntegerField(default=0, verbose_name='davolanish')),
                ('residence', models.PositiveIntegerField(default=0, verbose_name='doimiy yashash')),
                ('travel', models.PositiveIntegerField(default=0, verbose_name='sayohat')),
                ('wanted', models.PositiveIntegerField(default=0, verbose_name='qidiruvdagilar')),
                ('jailed', models.PositiveIntegerField(default=0, verbose_name='jazoni o‘tayotganlar')),
                ('missing', models.PositiveIntegerField(default=0, verbose_name='bedarak yo‘qolganlar')),
                ('remittance_amount', models.PositiveIntegerField(default=0, verbose_name='jo‘natma, mln $')),
                ('remittance_count', models.PositiveIntegerField(default=0, verbose_name='jo‘natmalar soni, ming')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='xavf indeksi')),
            ],
            options={
                'verbose_name': 'davlat',
                'verbose_name_plural': 'davlatlar',
                'ordering': ['-total', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nomi')),
                ('latitude', models.FloatField(verbose_name='kengligi')),
                ('longitude', models.FloatField(verbose_name='uzunligi')),
                ('departed', models.PositiveIntegerField(default=0, verbose_name='chiqqanlar')),
                ('returned', models.PositiveIntegerField(default=0, verbose_name='qaytganlar')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='xavf darajasi')),
            ],
            options={
                'verbose_name': 'hudud',
                'verbose_name_plural': 'hududlar',
                'ordering': ['-departed', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BorderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=180, verbose_name='punkt nomi')),
                ('outbound', models.PositiveIntegerField(default=0, verbose_name='chiqish')),
                ('inbound', models.PositiveIntegerField(default=0, verbose_name='kirish')),
                ('load_percent', models.PositiveSmallIntegerField(default=0, verbose_name='yuklama, %')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='border_points', to='geography.region', verbose_name='viloyat')),
            ],
            options={
                'verbose_name': 'o‘tkazish punkti',
                'verbose_name_plural': 'o‘tkazish punktlari',
                'ordering': ['-load_percent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=120, verbose_name='nomi')),
                ('departed', models.PositiveIntegerField(default=0, verbose_name='chiqqanlar')),
                ('returned', models.PositiveIntegerField(default=0, verbose_name='qaytganlar')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='xavf darajasi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geography.region', verbose_name='viloyat')),
            ],
            options={
                'verbose_name': 'tuman',
                'verbose_name_plural': 'tumanlar',
                'ordering': ['-departed', 'name'],
                'constraints': [models.UniqueConstraint(fields=('region', 'name'), name='unique_district_per_region')],
            },
        ),
    ]
