# Generated by Django 5.2.17 on 2026-08-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='consulate_helped',
            field=models.PositiveIntegerField(default=0, verbose_name='yordam ko‘rsatilgan'),
        ),
        migrations.AddField(
            model_name='country',
            name='consulate_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='konsullikka murojaatlar'),
        ),
        migrations.AddField(
            model_name='country',
            name='violation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='qonunbuzilish holatlari'),
        ),
        migrations.AddField(
            model_name='region',
            name='employed',
            field=models.PositiveIntegerField(default=0, verbose_name='ish bilan ta’minlangan'),
        ),
    ]
