# Generated by Django 5.2.17 on 2026-08-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsulateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('label', models.CharField(max_length=180, unique=True, verbose_name='xizmat turi')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='murojaatlar soni')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'konsullik xizmati',
                'verbose_name_plural': 'konsullik xizmatlari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='dastur nomi')),
                ('completed', models.PositiveIntegerField(default=0, verbose_name='bajarildi')),
                ('target', models.PositiveIntegerField(default=1, verbose_name='maqsad')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'reintegratsiya dasturi',
                'verbose_name_plural': 'reintegratsiya dasturlari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SosChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='kanal nomi')),
                ('share', models.PositiveSmallIntegerField(default=0, verbose_name='ulushi, %')),
                ('icon', models.CharField(default='phone', max_length=24, verbose_name='belgisi')),
            ],
            options={
                'verbose_name': 'SOS kanali',
                'verbose_name_plural': 'SOS kanallari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('key', models.SlugField(max_length=32, unique=True, verbose_name='kalit')),
                ('label', models.CharField(max_length=120, verbose_name='turi')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='holatlar soni')),
                ('delta', models.FloatField(default=0, verbose_name='o‘zgarish, %')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='coral', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'qonunbuzilish turi',
                'verbose_name_plural': 'qonunbuzilish turlari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SosEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='murojaat raqami')),
                ('applicant_name', models.CharField(max_length=180, verbose_name='murojaatchi')),
                ('city', models.CharField(max_length=120, verbose_name='shahar')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='kengligi')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='uzunligi')),
                ('event_type', models.CharField(max_length=180, verbose_name='murojaat turi')),
                ('severity', models.CharField(choices=[('critical', 'Kritik'), ('high', 'Shoshilinch'), ('mid', 'O‘rta'), ('low', 'Past')], default='high', max_length=16, verbose_name='jiddiyligi')),
                ('minutes_ago', models.PositiveIntegerField(default=0, verbose_name='necha daqiqa oldin')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='hal etilgan')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sos_events', to='geography.country', verbose_name='davlat')),
            ],
            options={
                'verbose_name': 'SOS murojaat',
                'verbose_name_plural': 'SOS murojaatlar',
                'ordering': ['minutes_ago', '-created_at'],
                'indexes': [models.Index(fields=['severity'], name='monitoring__severit_c1f822_idx')],
            },
        ),
    ]
