# Generated by Django 5.2.17 on 2026-08-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_country_consulate_helped_country_consulate_requests_and_more'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsulateCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='ish raqami')),
                ('applicant_name', models.CharField(blank=True, max_length=180, verbose_name='murojaatchi')),
                ('subject', models.CharField(max_length=180, verbose_name='murojaat mavzusi')),
                ('stage', models.CharField(choices=[('new', 'Yangi murojaatlar'), ('review', 'Ko‘rib chiqilmoqda'), ('waiting', 'Hujjat kutilmoqda'), ('closed', 'Yopilgan')], db_index=True, default='new', max_length=16, verbose_name='bosqichi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulate_cases', to='geography.country', verbose_name='davlat')),
            ],
            options={
                'verbose_name': 'konsullik ishi',
                'verbose_name_plural': 'konsullik ishlari',
                'ordering': ['stage', '-created_at'],
            },
        ),
    ]
