# Generated by Django 5.2.17 on 2026-08-22 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('tag', models.CharField(choices=[('O‘SISH', 'O‘sish'), ('ANOMALIYA', 'Anomaliya'), ('PROGNOZ', 'Prognoz'), ('IJOBIY', 'Ijobiy'), ('OGOHLANTIRISH', 'Ogohlantirish')], default='PROGNOZ', max_length=24, verbose_name='belgi')),
                ('title', models.CharField(max_length=250, verbose_name='sarlavha')),
                ('body', models.TextField(verbose_name='tavsif')),
                ('recommended_action', models.CharField(blank=True, max_length=250, verbose_name='tavsiya etilgan chora')),
                ('confidence', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ishonch, %')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'AI insayt',
                'verbose_name_plural': 'AI insaytlar',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('text', models.CharField(max_length=250, unique=True, verbose_name='savol matni')),
            ],
            options={
                'verbose_name': 'AI savoli',
                'verbose_name_plural': 'AI savollari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='tizim nomi')),
                ('status', models.CharField(choices=[('Ulangan', 'Ulangan'), ('Sinovda', 'Sinovda'), ('Rejada', 'Rejada')], default='Rejada', max_length=16, verbose_name='holati')),
            ],
            options={
                'verbose_name': 'integratsiya',
                'verbose_name_plural': 'integratsiyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('group', models.CharField(choices=[('dashboard', 'Boshqaruv paneli'), ('consulate', 'Konsullik'), ('return', 'Qaytish'), ('border', 'Chegara'), ('sos', 'SOS xizmati'), ('audit', 'Audit')], db_index=True, max_length=16, verbose_name='guruh')),
                ('key', models.SlugField(blank=True, max_length=40, verbose_name='kalit')),
                ('label', models.CharField(max_length=180, verbose_name='ko‘rsatkich nomi')),
                ('value', models.BigIntegerField(default=0, verbose_name='qiymati')),
                ('delta', models.FloatField(default=0, verbose_name='o‘zgarish, %')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='izoh')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'ko‘rsatkich',
                'verbose_name_plural': 'ko‘rsatkichlar',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportArchiveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('name', models.CharField(max_length=250, verbose_name='hisobot nomi')),
                ('size', models.CharField(blank=True, max_length=32, verbose_name='hajmi')),
                ('generated_on', models.DateField(blank=True, null=True, verbose_name='sanasi')),
                ('generated_by', models.CharField(blank=True, max_length=64, verbose_name='kim shakllantirgan')),
            ],
            options={
                'verbose_name': 'arxiv yozuvi',
                'verbose_name_plural': 'hisobot arxivi',
                'ordering': ['-generated_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='shablon nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsifi')),
                ('period', models.CharField(choices=[('Kunlik', 'Kunlik'), ('Haftalik', 'Haftalik'), ('Oylik', 'Oylik'), ('Choraklik', 'Choraklik'), ('Yillik', 'Yillik')], default='Oylik', max_length=16, verbose_name='davriyligi')),
                ('formats', models.CharField(default='XLSX, PDF', max_length=90, verbose_name='formatlar')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'hisobot shabloni',
                'verbose_name_plural': 'hisobot shablonlari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('key', models.SlugField(max_length=32, unique=True, verbose_name='kalit')),
                ('label', models.CharField(max_length=180, verbose_name='omil nomi')),
                ('weight', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='vazni, %')),
            ],
            options={
                'verbose_name': 'model omili',
                'verbose_name_plural': 'model omillari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('group', models.CharField(choices=[('composition', 'Migrantlar tarkibi'), ('purpose', 'Chiqish maqsadi'), ('risk', 'Xavf taqsimoti')], db_index=True, max_length=16, verbose_name='guruh')),
                ('key', models.SlugField(blank=True, max_length=40, verbose_name='kalit')),
                ('label', models.CharField(max_length=180, verbose_name='nomi')),
                ('value', models.BigIntegerField(default=0, verbose_name='qiymati')),
                ('tone', models.CharField(choices=[('turk', 'Firuza'), ('lapis', 'Ko‘k'), ('saffron', 'Sariq'), ('coral', 'Marjon'), ('violet', 'Binafsha'), ('mist', 'Kulrang')], default='lapis', max_length=16, verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'taqsimot bo‘lagi',
                'verbose_name_plural': 'taqsimot bo‘laklari',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan")),
                ('key', models.SlugField(max_length=32, unique=True, verbose_name='kalit')),
                ('name', models.CharField(max_length=120, verbose_name='qator nomi')),
                ('color', models.CharField(default='var(--turk)', max_length=32, verbose_name='rangi')),
                ('monthly_values', models.JSONField(default=list, verbose_name='oylik qiymatlar')),
            ],
            options={
                'verbose_name': 'grafik qatori',
                'verbose_name_plural': 'grafik qatorlari',
                'ordering': ['key'],
            },
        ),
    ]
